EVEREST_DATE_YEAR := $(shell date -u +%Y)
EVEREST_DATE_MONTH := $(shell date -u +%m)
EVEREST_DATE_DAY := $(shell date -u +%d)
EVEREST_DATE_HOUR := $(shell date -u +%H)
EVEREST_DATE_MINUTE := $(shell date -u +%M)
EVEREST_BUILD_DATE_UTC := $(shell date -d '$(EVEREST_DATE_YEAR)-$(EVEREST_DATE_MONTH)-$(EVEREST_DATE_DAY) $(EVEREST_DATE_HOUR):$(EVEREST_DATE_MINUTE) UTC' +%s)
EVEREST_BUILD_DATE := $(EVEREST_DATE_YEAR)$(EVEREST_DATE_MONTH)$(EVEREST_DATE_DAY)-$(EVEREST_DATE_HOUR)$(EVEREST_DATE_MINUTE)

EVEREST_DISPLAY_VERSION := 2.0

EVEREST_PLATFORM_VERSION := 15.0

EVEREST_VERSION := v$(EVEREST_DISPLAY_VERSION)-$(EVEREST_BUILD)-$(EVEREST_PLATFORM_VERSION)-$(EVEREST_BUILD_DATE)

# EVEREST Platform Version
PRODUCT_SYSTEM_DEFAULT_PROPERTIES += \
    ro.everest.build.date=$(BUILD_DATE) \
    ro.everest.device=$(EVEREST_BUILD) \
    ro.everest.fingerprint=$(ROM_FINGERPRINT) \
    ro.everest.version=$(EVEREST_VERSION) \
    ro.modversion=$(EVEREST_VERSION)

# Signing
-include vendor/everest-priv/keys/keys.mk
